services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: hackathon_db
      POSTGRES_USER: hackathon_user
      POSTGRES_PASSWORD: hackathon_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hackathon_user -d hackathon_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

# Para usar apenas o banco de dados em desenvolvimento:
# docker-compose -f docker-compose.dev.yml up -d db
# 
# Isso permite rodar npm run dev localmente sem conflitos,
# enquanto usa o PostgreSQL containerizado.